---
api:
  url: https://uat-fhir.followmyhealth.com/api/
  patient: c5f9d7f2-9927-4904-aab2-a62d0157b807

auth:
  strategy: authorization_code
  client_id: 0c9cc532-9ac5-48cf-998e-3b9da5394b55
  # client_secret intentionally included
  client_secret: D9rE+xExGY7ZhW6aJJFloDjIoaBZVwguHXSIlUzcX/MEVBGU8S+eUCk44YHWYDTQuL4Gt9P/wlfPsHSM+dVoKA==
  scope: launch/patient patient/*.read offline_access
  confidential_client: True
  steps:
    - find: "[translate='DEFAULT_LOGIN_BUTTON']"
    - click
    - find: "#UserName"
    - type: "s4s_6-22-16"
    - find: "#Password"
    - type: "s4s!2345"
    - find: "[translate='Login_LogIn']"
    - click
