---
api:
  versions:
    STU3:
      url: https://dev.bluebutton.cms.fhirservice.net/protected/bluebutton/fhir/v1/
      patient: 3979

use_cases:
  security: STU3
  financial: STU3

auth:
  versions:
    STU3:
      strategy: authorization_code
      client_id: CyoUBUTARbvicAujJjeNwPF6bKeKMywUrJSbfnp8
      # client_secret intentionally included
      client_secret: hiD2RapR14bkdPERUnyPXEUoWA1fKLitoacHvmyI3igAmXuMbV8JenQjo6LI1lQwuEeToHzbameF8dIth2QxZ0KVswAXzGKe3yWMwbhGcri4pXAVAeAe5zmaQPWgyJYP
      scope: profile patient/Patient.read patient/ExplanationOfBenefit.read patient/Coverage.read
      confidential_client: True
      sign_in_steps:
        - element: "#id_username"
          send_keys: "s4s-test-suite"
        - element: "#id_password"
          send_keys: "cms-demo"
        - element: "input[type='submit']"
          click: True
      authorize_steps:
        - element: "input[value='Approve']"
          execute_script: $("input[value='Approve']").click()
      cancel_steps:
        - element: "button.deny"
          click: True
      revoke_url: https://dev.bluebutton.cms.fhirservice.net/o/authorized_tokens/
      revoke_steps:
        - element: "[title~=test][value~=Remove]"
          click: True
