---
api:
  versions:
    STU3:
      url: https://sandbox.bluebutton.cms.gov/v1/fhir/

use_cases:
  security: STU3
  financial: STU3

auth:
  versions:
    STU3:
      strategy: authorization_code
      client_id: CyoUBUTARbvicAujJjeNwPF6bKeKMywUrJSbfnp8
      # client_secret intentionally included
      client_secret: hiD2RapR14bkdPERUnyPXEUoWA1fKLitoacHvmyI3igAmXuMbV8JenQjo6LI1lQwuEeToHzbameF8dIth2QxZ0KVswAXzGKe3yWMwbhGcri4pXAVAeAe5zmaQPWgyJYP
      scope: profile patient/Patient.read patient/ExplanationOfBenefit.read patient/Coverage.read
      redirect_uri: http://tests.dev.syncfor.science:9003/authorized/
      confidential_client: True
      sign_in_steps:
        - element: "#SWEUserName"
          send_keys: "BBUser00000"
        - element: "#SWEPassword"
          send_keys: "PW00000!"
        - element: "#SignIn"
          execute_script: |
            jQuery('#SignIn').click();
      authorize_steps:
        - element: "#approve"
          click: True
      cancel_steps:
        - element: "#theform a.ds-c-button"
          click: True
      revoke_url: https://sandbox.bluebutton.cms.gov/o/authorized_tokens/
      revoke_steps:
        - element: "[title~=test][value~=Remove]"
          click: True
