---
api:
  url: http://52.22.98.192:8080/FHIRServer/fhir/HEFBCA
  patient: 9128

auth:
  strategy: authorization_code
  client_id: "c0c7c76d30bd3dcaefc96f40275bdc0a"
  # client_secret intentionally included
  client_secret: "f9d08bf18de3ea87603c54ee50fbc495"
  scope: launch/patient patient/*.read offline_access
  confidential_client: True
  sign_in_steps:
    - element: '#uname'
      send_keys: 'user1'
    - element: '#password'
      send_keys: 'Password2'
    - element: '#btnSubmit'
      click: True
  authorize_steps:
    - element: '#grant_clicked'
      click: True
  cancel_steps:
    - element: '#cancel_clicked'
      click: True
