---
api:
  versions:
    DSTU2:
      url: http://smart:5000/api/fhir/

use_cases:
  security: DSTU2
  ehr: DSTU2

auth:
  versions:
    DSTU2:
      strategy: authorization_code
      client_id: test-suite
      # client_secret intentionally included
      client_secret: demo-secret-s4s
      scope: launch/patient patient/*.read offline_access
      redirect_uri: http://tests.dev.syncfor.science:9003/authorized/
      confidential_client: True
      sign_in_steps:
        - element: '#sign-in'
          click: True
      authorize_steps:
        - element: "[data-patient-id=smart-1288992]"
          optional: True
          click: True
          wait: 2
        - element: "[data-slide=next]"
          optional: True
          click: True
          wait: 2
        - element: "[type=checkbox]"
          optional: True
          execute_script: |
            Array.from(document.querySelectorAll('input.glyphbox')).forEach(function(el) { el.disabled=false; });
            Array.from(document.querySelectorAll('input.glyphbox')).forEach(function(el) { el.checked=true; });
            Array.from(document.querySelectorAll('button[data-slide=next]')).forEach(function(el) { el.disabled=false; });
            Array.from(document.querySelectorAll('button[data-slide=next]'))[1].click();
        - element: "#authorize"
          optional: True
          click: True
          wait: 2

